name: Python Package

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # specify the version you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        python -m twine check dist/*
        python -m twine upload --repository pypi dist/*
